name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  blocify:
    path: ../
  
  flutter_bloc: ^4.0.0
  dio: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
